import React, { useState, useEffect } from 'react';
import img from './img.jpg' // Import local image
import img1 from './img1.jpg' // Import local image
import img3 from './img3.jpg' // Import local image
import img4 from './img4.jpg' // Import local image
//import g3india from './g3india.jpg'
import { Grid, Typography } from '@mui/material';


const HomeContent = () => {
    const imageUrls = [img, img1, img3, img4];  // Array of locally imported images

    const [currentImageIndex, setCurrentImageIndex] = useState(0);

    useEffect(() => {
        const intervalId = setInterval(() => {
            setCurrentImageIndex((prevIndex) => (prevIndex + 1) % imageUrls.length);
        }, 3000); // Change image every 3 seconds (adjust the interval as needed)

        return () => clearInterval(intervalId);
    }, [currentImageIndex, imageUrls.length]);

    return (
        <div>
            <img src={imageUrls[currentImageIndex]} alt={`Image ${currentImageIndex + 1}`} style={{ width: '75%', height: '500px' }} />
            <p>Messages are communications provided on the screen to the screen viewer.
                Screen messages fall into two broad categories: system and instructional.
                System messages are generated by the <b>system to keep the user informed of the system’s</b> state and activities.
                Instructional messages, sometimes referred to as prompting messages, are messages that tell the user how to work with, or complete, the screen displayed.</p>
            {/* <Grid container spacing={2}>
                <Grid item xs={4} >
                    <img src='./sam.jpg' style={{ height: '400px', width: '400px' }} />
                    <Typography>Sam Chappid </Typography>
                    <Typography>Founder and CEO</Typography>
                </Grid>
                <Grid item xs={4}>
                    <img src='./anurag.jpg' style={{ height: '400px', width: '400px' }} />
                    <Typography>Anurag Vaishy </Typography>
                    <Typography>Solution Architect</Typography>
                </Grid>
                <Grid item xs={4}>
                    <img src='./amit.jpg' style={{ height: '400px', width: '400px' }} />
                    <Typography>Amit Trivedi </Typography>
                    <Typography>Senior Software Engineer</Typography>
                </Grid>
                <Grid item xs={4}>
                    <img src='./kapil.jpg' style={{ height: '400px', width: '400px' }} />
                    <Typography>Kapil Trivedi </Typography>
                    <Typography>Senior Software Engineer</Typography>
                </Grid>
                <Grid item xs={4}>
                    <img src='./hitesh.jpg' style={{ height: '400px', width: '400px' }} />
                    <Typography>Hiteh Joshi </Typography>
                    <Typography>Senior Software Engineer</Typography>
                </Grid>
                <Grid item xs={4}>
                    <img src='./srikanth.jpg' style={{ height: '400px', width: '400px' }} />
                    <Typography>Srikanth Bethi</Typography>
                    <Typography>Junior Software Engineer</Typography>
                </Grid>
            </Grid> */}
        </div>
    );
};

export default HomeContent;
